### ISSUE TITLE
Modbus write V1.1.2 - icon is not editable

### ISSUE THREAD

**Issue by Domot** [DomoticX/domoticz-modbus#14] opened 2019-05-11 22:26 UTC
In modbus-read I can change the icon. In modbus-write I can select another icon but it can't be saved.

**Comment by cezarysz** [comment] 2019-05-12 19:57
> In modbus-read I can change the icon. In modbus-write I can select another icon but it can't be saved.

It's not caused by script. It must be something in Domoticz DB.

**Comment by DomoticX** [comment] 2020-05-06 13:30
Maybe this is fixed in Domoticz 2020.2?, not a plugin issue.

**Closed as completed by DomoticX** 2020-05-06 13:30 UTC
