### ISSUE TITLE
Read Relay Status - RTU

### ISSUE THREAD

**Issue by grasuoare** [DomoticX/domoticz-modbus#17] opened 2019-07-22 18:58 UTC
Hi there. I'm trying to read the status of the relays ([relay board](http://domoticx.com/modbus-relaisbord/) that is testet for this) trough RTU Mode and i get the following error logs:

 2019-07-23 14:41:46.506 (test) Modbus error decoding or received no data (RTU/ASCII/RTU over TCP)!, check your settings!
2019-07-23 14:41:46.507 Debug: SQLH UpdateValueInt test - HwID:7 DevID:00070001 Type:243 sType:31 nValue:0 sValue:0 

Could you help me with this issue?
![relay-read](https://user-images.githubusercontent.com/20748661/61657539-da297780-accb-11e9-8947-5e1c49774412.jpg)

**Comment by cezarysz** [comment] 2019-07-23 05:54
Did you try to change sensor type to "custom"? What's the value of sensor then?

**Comment by grasuoare** [comment] 2019-07-23 11:43
with custom is the same: 
 2019-07-23 14:43:12.156 (test) Modbus error decoding or received no data (RTU/ASCII/RTU over TCP)!, check your settings!
2019-07-23 14:43:12.157 Debug: SQLH UpdateValueInt test - HwID:7 DevID:00070001 Type:243 sType:31 nValue:0 sValue:0

**Comment by cezarysz** [comment] 2019-07-23 11:55
Sorry I've similar problem with devices. I sure this is script problem.

wt., 23 lip 2019 o 13:43 grasuoare <notifications@github.com> napisał(a):

**Comment by cezarysz** [comment] 2019-07-23 15:53
I solved my problem by adding data.registers in pymodbus section
try it in decoder you use
https://github.com/DomoticX/domoticz-modbus/pull/16


wt., 23 lip 2019 o 13:54 Cezary Szymanski <cezarysz84@gmail.com> napisał(a):

**Comment by grasuoare** [comment] 2019-07-23 17:24
i tried adding .registers for the 3 lines mentioned and same error log:

2019-07-23 20:23:18.039 (test) Modbus error decoding or received no data (RTU/ASCII/RTU over TCP)!, check your settings!
2019-07-23 20:23:18.040 Debug: SQLH UpdateValueInt test - HwID:7 DevID:00070001 Type:243 sType:31 nValue:0 sValue:0

**Comment by grasuoare** [comment] 2019-07-23 21:39
p.s at every reading i see that the communication led from the relay board blinks.

**Comment by grasuoare** [comment] 2019-07-24 18:20
Guys, any news about this? could somebody tell me what to do or what am i doing wrong? Thanks in advance

**Comment by cezarysz** [comment] 2019-07-24 19:42
Try to change data type. I think the problem is in data convertion for
"noco".

śr., 24 lip 2019 o 20:20 grasuoare <notifications@github.com> napisał(a):

**Comment by cezarysz** [comment] 2019-07-24 20:54
In my case  Modbus RTU/ASCII/TCP - READ v1.1.3 is working good when reading
"No conversion (1register) data type". Please try it,

śr., 24 lip 2019 o 21:42 Cezary Szymanski <cezarysz84@gmail.com> napisał(a):

**Comment by grasuoare** [comment] 2019-07-25 18:11
i tried all data types. same result.

**Comment by cezarysz** [comment] 2019-07-26 05:05
> i tried all data types. same result.

Did you tryed to read "no conversion data type register" using plugin v1.1.3?

**Comment by grasuoare** [comment] 2019-07-29 15:50
Hi cezarysz,

I just added the plugin v1.1.3. Same error.  Check image with the settings:
![relay-read](https://user-images.githubusercontent.com/20748661/62062410-a3a2ae00-b231-11e9-9f90-5193caad6d33.jpg)


2019-07-29 18:46:37.328 (test4) Modbus error decoding or recieved no data (RTU/ASCII/RTU over TCP)!, check your settings!

**Comment by Antikillerbm** [comment] 2019-07-30 09:03
I got the same error in modbus RTU mode only. 
Even discrete inputs not working

**Comment by cezarysz** [comment] 2019-07-30 10:38
Did you try to read registers using plugin v1.1.3?

wt., 30 lip 2019 o 11:03 Antikillerbm <notifications@github.com> napisał(a):

**Comment by Antikillerbm** [comment] 2019-07-30 12:00
Not yet. I have no possibility to check now sorry

**Comment by grasuoare** [comment] 2019-07-31 17:04
> 
> 
> Not yet. I have no possibility to check now sorry

We are all waiting. Thank you for this plugin!

**Comment by DomoticX** [comment] 2020-05-05 18:53
In update Modbus READ 2020.2A lot has been changed also added BOOL option, closing this one...

**Closed as completed by DomoticX** 2020-05-05 18:53 UTC

**Comment by awalsum** [comment] 2022-10-28 10:06
I have been trying to use the BOOL option, but it isn't working for me. I keep getting errors saying that no data received etc. I am using this plugin to read various INT and FLOAT values with function 1 and 3 and that works well. I also use the Write plugin and that works well too. I have tried to find the cause of the BOOL not working in this script, but can't lay my finger on it.
